import streamlit as st
import pandas as pd
import smtplib
from email.mime.text import MIMEText
import os
import sys
import json
from datetime import datetime, date

# Thêm thư mục gốc vào path để import utils
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from utils import (
    check_login_required,
    should_send_email,
    mark_email_sent,
    clear_email_history,
    load_email_history,
    prune_email_history_for_safe_products,
    render_main_sidebar,
    load_email_events,
    log_email_event,
)

from st_aggrid import AgGrid, GridOptionsBuilder, GridUpdateMode

# ======================
# CẤU HÌNH TRANG
# ======================
st.set_page_config(
    page_title="Cảnh báo tồn kho",
    page_icon="⚠️",
    layout="wide",
)

# ======================
# ĐĂNG NHẬP + SIDEBAR
# ======================
check_login_required()
render_main_sidebar()

# ======================
# ĐƯỜNG DẪN DATABASE
# ======================
DB_PATH = "database/sanpham.csv"
if not os.path.exists(DB_PATH):
    st.error("❌ Chưa có dữ liệu sản phẩm. Vui lòng thêm sản phẩm trước.")
    st.info("💡 Vui lòng vào trang **Sản Phẩm** để thêm sản phẩm.")
    st.stop()

# ======================
# LOAD & SAVE
# ======================
def load_data():
    df = pd.read_csv(DB_PATH)

    if "auto_unique_id" in df.columns:
        df = df.rename(columns={"auto_unique_id": "STT"})
    if "autoGeneratedId" in df.columns:
        df = df.rename(columns={"autoGeneratedId": "STT"})

    return df

def save_data(df):
    df.to_csv(DB_PATH, index=False)
    st.cache_data.clear()  # Clear tất cả cache để trang Products cũng cập nhật


# ======================
# LỊCH SỬ GỬI EMAIL HẠN SỬ DỤNG (TRÁNH GỬI LẶP)
# ======================
EXPIRY_SIGNATURE_FILE = "email_expiry_signature.json"


def load_expiry_signature():
    if os.path.exists(EXPIRY_SIGNATURE_FILE):
        try:
            with open(EXPIRY_SIGNATURE_FILE, "r", encoding="utf-8") as f:
                data = json.load(f)
                return data.get("signature", "")
        except Exception:
            return ""
    return ""


def save_expiry_signature(signature: str):
    try:
        with open(EXPIRY_SIGNATURE_FILE, "w", encoding="utf-8") as f:
            json.dump({"signature": signature}, f, ensure_ascii=False, indent=2)
    except Exception:
        pass


# ======================
# HÀM TÍNH CẢNH BÁO HẠN SỬ DỤNG THEO LÔ
# ======================
def build_lot_expiry_alerts(df_products, days_threshold=60):
    """
    Tạo bảng cảnh báo lô hàng sắp hết hạn sử dụng (HSD còn dưới days_threshold ngày).
    Đọc trực tiếp từ warehouse_areas.csv để đảm bảo số lô và số lượng khớp với trang Khu Vực Kho.
    Bỏ logic FEFO, chỉ đọc số lượng còn lại từ warehouse_areas.csv.
    """
    import_db_path = "database/phieu_nhap.csv"
    export_db_path = "database/phieu_xuat.csv"
    warehouse_areas_path = "database/warehouse_areas.csv"
    
    # Đọc warehouse_areas.csv - đây là nguồn dữ liệu chính
    warehouse_assignments = pd.DataFrame()
    if os.path.exists(warehouse_areas_path):
        try:
            warehouse_assignments = pd.read_csv(warehouse_areas_path)
            if not warehouse_assignments.empty:
                warehouse_assignments["Mã sản phẩm"] = warehouse_assignments["Mã sản phẩm"].astype(str)
                warehouse_assignments["Lô"] = pd.to_numeric(warehouse_assignments["Lô"], errors="coerce").fillna(0).astype(int)
                warehouse_assignments["Số lượng"] = pd.to_numeric(warehouse_assignments.get("Số lượng", 0), errors="coerce").fillna(0).astype(int)
                warehouse_assignments = warehouse_assignments[warehouse_assignments["Số lượng"] > 0]  # Chỉ lấy các dòng còn số lượng
        except Exception:
            warehouse_assignments = pd.DataFrame()

    if warehouse_assignments.empty:
        return pd.DataFrame()

    # Đọc phiếu nhập để lấy thông tin HSD và Ngày nhập
    if os.path.exists(import_db_path):
        df_import_all = pd.read_csv(import_db_path)
    else:
        df_import_all = pd.DataFrame()

    if os.path.exists(export_db_path):
        df_export_all = pd.read_csv(export_db_path)
    else:
        df_export_all = pd.DataFrame()

    alerts = []
    today = date.today()

    # Tạo mapping từ (Mã sản phẩm, Lô) -> thông tin từ phiếu nhập
    import_info_map = {}
    if not df_import_all.empty and "Mã sản phẩm" in df_import_all.columns:
        for ma_sp in warehouse_assignments["Mã sản phẩm"].unique():
            df_sp_imports = df_import_all[
                df_import_all["Mã sản phẩm"].astype(str) == str(ma_sp)
            ].copy()
            
            if not df_sp_imports.empty:
                # Sắp xếp theo ngày nhập
                if "Ngày nhập" in df_sp_imports.columns:
                    df_sp_imports["_dt"] = pd.to_datetime(
                        df_sp_imports["Ngày nhập"], errors="coerce", dayfirst=True
                    )
                    df_sp_imports = df_sp_imports.sort_values(by="_dt").reset_index(drop=True)
                
                # Đánh số lô theo thứ tự nhập (1, 2, 3, ...) - không có lô ảo
                for idx, row in df_sp_imports.iterrows():
                    lot_num = idx + 1  # Lô bắt đầu từ 1
                    import_info_map[(str(ma_sp), lot_num)] = {
                        "Hạn sử dụng": str(row.get("Hạn sử dụng", "")),
                        "Ngày nhập": str(row.get("Ngày nhập", "")),
                    }

    # Kiểm tra xem sản phẩm có lô ảo INIT không (để map số lô đúng)
    def has_initial_lot(ma_sp, df_products, df_imports, df_exports):
        product_row = df_products[df_products["Mã sản phẩm"].astype(str) == str(ma_sp)]
        if product_row.empty:
            return False
        try:
            current_stock = int(product_row.iloc[0].get("Số lượng tồn kho", 0))
        except Exception:
            current_stock = 0

        if "Mã sản phẩm" in df_imports.columns:
            df_imp = df_imports[df_imports["Mã sản phẩm"].astype(str) == str(ma_sp)].copy()
        else:
            df_imp = pd.DataFrame()

        if "Mã sản phẩm" in df_exports.columns:
            df_exp = df_exports[df_exports["Mã sản phẩm"].astype(str) == str(ma_sp)].copy()
        else:
            df_exp = pd.DataFrame()

        total_imported = 0
        if not df_imp.empty and "Số lượng nhập" in df_imp.columns:
            total_imported = (
                pd.to_numeric(df_imp["Số lượng nhập"], errors="coerce")
                .fillna(0)
                .astype(int)
                .sum()
            )

        total_exported = 0
        if not df_exp.empty:
            total_exported = (
                pd.to_numeric(df_exp["Số lượng xuất"], errors="coerce")
                .fillna(0)
                .astype(int)
                .sum()
            )

        initial_qty = current_stock - total_imported + total_exported
        return initial_qty > 0

    # Xử lý từng sản phẩm trong warehouse_areas.csv
    for ma_sp in warehouse_assignments["Mã sản phẩm"].unique():
        ma_sp = str(ma_sp).strip()
        if not ma_sp:
            continue

        # Lấy thông tin sản phẩm
        product_row = df_products[df_products["Mã sản phẩm"].astype(str) == ma_sp]
        if product_row.empty:
            continue
        ten_sp = product_row.iloc[0].get("Tên sản phẩm", "")

        # Kiểm tra xem có lô ảo INIT không
        has_init = has_initial_lot(ma_sp, df_products, df_import_all, df_export_all)

        # Lấy tất cả các lô của sản phẩm này từ warehouse_areas.csv
        df_sp_lots = warehouse_assignments[
            warehouse_assignments["Mã sản phẩm"] == ma_sp
        ].copy()

        # Gom nhóm theo Lô để tổng hợp số lượng từ tất cả các khu
        lot_summary = {}
        for _, row in df_sp_lots.iterrows():
            lo_warehouse = int(row["Lô"])  # Lô trong warehouse_areas.csv (1, 2, 3...)
            so_luong = int(row["Số lượng"])
            khu = str(row.get("Khu", ""))
            
            if lo_warehouse not in lot_summary:
                lot_summary[lo_warehouse] = {
                    "so_luong": 0,
                    "is_in_khu_e": False,
                }
            
            lot_summary[lo_warehouse]["so_luong"] += so_luong
            if khu == "Khu E":
                lot_summary[lo_warehouse]["is_in_khu_e"] = True

        # Tạo cảnh báo cho từng lô
        for lo_warehouse, lot_info in lot_summary.items():
            so_luong = lot_info["so_luong"]
            is_in_khu_e = lot_info["is_in_khu_e"]
            
            if so_luong <= 0:
                continue

            # Map số lô từ warehouse_areas.csv sang số lô hiển thị (có tính đến lô ảo INIT)
            if has_init:
                # Có lô ảo INIT: warehouse_areas.csv lô 1 -> hiển thị lô 2
                display_lot = lo_warehouse + 1
            else:
                # Không có lô ảo INIT: giữ nguyên
                display_lot = lo_warehouse

            # Lấy thông tin HSD và Ngày nhập từ phiếu nhập
            import_info = import_info_map.get((ma_sp, lo_warehouse), {})
            hsd_str = import_info.get("Hạn sử dụng", "")
            ngay_nhap = import_info.get("Ngày nhập", "")

            # Nếu không có HSD thì bỏ qua (không cảnh báo)
            if not hsd_str or hsd_str.strip() == "" or hsd_str.lower() == "nan":
                continue

            # Parse HSD để kiểm tra
            try:
                hsd_dt = datetime.strptime(hsd_str, "%d/%m/%Y").date()
            except Exception:
                continue

            days_to_expiry = (hsd_dt - today).days

            # Chỉ cảnh báo các lô còn < days_threshold ngày (kể cả đã quá hạn)
            if days_to_expiry > days_threshold:
                continue

            if days_to_expiry < 0:
                canh_bao_text = f"ĐÃ HẾT HẠN {-days_to_expiry} ngày"
            else:
                canh_bao_text = f"Còn {days_to_expiry} ngày"

            # Xác định trạng thái
            if is_in_khu_e:
                trang_thai = "Đã chuyển sang Khu E"
            else:
                trang_thai = "Chưa xử lí"

            # Tình trạng: luôn là "còn dư" vì đã lọc từ warehouse_areas.csv (chỉ có lô còn số lượng > 0)
            tinh_trang = f"còn dư {so_luong}"

            alerts.append(
                {
                    "Lô": display_lot,
                    "Mã sản phẩm": ma_sp,
                    "Tên sản phẩm": ten_sp,
                    "Số lượng tồn kho": so_luong,
                    "Ngày nhập": ngay_nhap,
                    "Hạn sử dụng": hsd_str,
                    "Tình trạng": tinh_trang,
                    "Cảnh báo": canh_bao_text,
                    "Trạng thái": trang_thai,
                    "_is_in_khu_e": is_in_khu_e,  # Dùng để render màu sắc
                }
            )

    if not alerts:
        return pd.DataFrame()

    return pd.DataFrame(alerts)

# ======================
# HÀM GỬI EMAIL CẢNH BÁO ROP
# ======================
def send_email(products):
    try:
        if "email_sender" not in st.secrets:
            return False
        
        sender = st.secrets["email_sender"]
        password = st.secrets["email_password"]
        receiver = st.secrets["email_receiver"]

        # Tạo subject + nội dung email chuyên nghiệp
        total = len(products)
        subject = f"[CẢNH BÁO TỒN KHO] {total} sản phẩm dưới ngưỡng ROP"

        # Tạo bảng HTML liệt kê sản phẩm
        rows_html = ""
        for idx, p in enumerate(products, start=1):
            rows_html += f"""
                <tr>
                    <td style="padding: 6px 12px; border: 1px solid #e5e7eb;">{idx}</td>
                    <td style="padding: 6px 12px; border: 1px solid #e5e7eb;">{p['ma_sp']}</td>
                    <td style="padding: 6px 12px; border: 1px solid #e5e7eb;">{p['ten_sp']}</td>
                    <td style="padding: 6px 12px; border: 1px solid #e5e7eb; text-align: right;">{p['ton_kho']}</td>
                    <td style="padding: 6px 12px; border: 1px solid #e5e7eb; text-align: right;">{p['rop']}</td>
                </tr>
            """

        body = f"""
        <html>
        <body style="font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; color:#111827;">
            <h2 style="color:#b91c1c;">⚠ CẢNH BÁO TỒN KHO DƯỚI NGƯỠNG ROP</h2>
            <p>Xin chào Anh/Chị,</p>
            <p>
                Hệ thống ghi nhận hiện vẫn còn <strong>{total}</strong> sản phẩm
                <strong>chưa đạt tới ngưỡng tồn kho an toàn (ROP)</strong>
                sau các lần nhập/xuất gần đây.
            </p>
            <p>Cụ thể danh sách các sản phẩm cần ưu tiên bổ sung như sau:</p>
            <table style="border-collapse: collapse; margin-top: 8px; font-size: 14px;">
                <thead>
                    <tr style="background-color:#eff6ff;">
                        <th style="padding: 6px 12px; border: 1px solid #e5e7eb;">STT</th>
                        <th style="padding: 6px 12px; border: 1px solid #e5e7eb;">Mã sản phẩm</th>
                        <th style="padding: 6px 12px; border: 1px solid #e5e7eb;">Tên sản phẩm</th>
                        <th style="padding: 6px 12px; border: 1px solid #e5e7eb;">Tồn hiện tại</th>
                        <th style="padding: 6px 12px; border: 1px solid #e5e7eb;">ROP</th>
                    </tr>
                </thead>
                <tbody>
                    {rows_html}
                </tbody>
            </table>
            <p style="margin-top:16px;">
                Đề nghị Anh/Chị kiểm tra kế hoạch nhập hàng và tiếp tục bổ sung cho tới khi tồn kho
                của các sản phẩm trên đạt hoặc vượt mức ROP đã thiết lập, nhằm tránh thiếu hụt và gián đoạn bán hàng.
            </p>
            <p style="color:#6b7280; font-size:12px; margin-top:24px;">
                Email được gửi tự động từ hệ thống quản lý kho. Vui lòng không trả lời email này.
            </p>
        </body>
        </html>
        """

        msg = MIMEText(body, "html", "utf-8")
        msg["Subject"] = subject
        msg["From"] = sender
        msg["To"] = receiver

        with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
            server.login(sender, password)
            server.sendmail(sender, receiver, msg.as_string())

        return True

    except Exception as e:
        st.warning(f"⚠ Không thể gửi email cảnh báo: {str(e)}")
        return False


# ======================
# HÀM GỬI EMAIL CẢNH BÁO HẠN SỬ DỤNG
# ======================
def log_expiry_email_event(lot_rows):
    """
    Ghi lại một LẦN gửi email cảnh báo hạn sử dụng.
    lot_rows: list[dict] với các key: Lô, Mã sản phẩm, Tên sản phẩm, Số lượng tồn kho, Ngày nhập, Hạn sử dụng, Cảnh báo
    """
    events = load_email_events()
    events.append(
        {
            "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            "type": "EXPIRY",  # Phân biệt với ROP
            "count": len(lot_rows),
            "lots": lot_rows,  # Lưu thông tin lô hàng
        }
    )
    # Sử dụng hàm save_email_events từ utils
    from utils import save_email_events
    save_email_events(events)


def send_expiry_email(lot_rows):
    """
    Gửi email cảnh báo các LÔ HÀNG sắp hết hạn sử dụng.
    lot_rows: list[dict] với các key:
        - lo, ma_sp, ten_sp, so_luong, ngay_nhap, han_sd, canh_bao
    """
    try:
        if "email_sender" not in st.secrets:
            return False

        sender = st.secrets["email_sender"]
        password = st.secrets["email_password"]
        receiver = st.secrets["email_receiver"]

        total = len(lot_rows)
        subject = f"[CẢNH BÁO HẠN SỬ DỤNG] {total} lô hàng sắp hoặc đã hết hạn"

        rows_html = ""
        for idx, r in enumerate(lot_rows, start=1):
            rows_html += f"""
                <tr>
                    <td style="padding: 6px 12px; border: 1px solid #e5e7eb; text-align:center;">{idx}</td>
                    <td style="padding: 6px 12px; border: 1px solid #e5e7eb; text-align:center;">{r.get('Lô', '')}</td>
                    <td style="padding: 6px 12px; border: 1px solid #e5e7eb;">{r.get('Mã sản phẩm', '')}</td>
                    <td style="padding: 6px 12px; border: 1px solid #e5e7eb;">{r.get('Tên sản phẩm', '')}</td>
                    <td style="padding: 6px 12px; border: 1px solid #e5e7eb; text-align:right;">{r.get('Số lượng tồn kho', '')}</td>
                    <td style="padding: 6px 12px; border: 1px solid #e5e7eb;">{r.get('Ngày nhập', '')}</td>
                    <td style="padding: 6px 12px; border: 1px solid #e5e7eb;">{r.get('Hạn sử dụng', '')}</td>
                    <td style="padding: 6px 12px; border: 1px solid #e5e7eb; color:#b91c1c; font-weight:600;">{r.get('Cảnh báo', '')}</td>
                </tr>
            """

        body = f"""
        <html>
        <body style="font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; color:#111827;">
            <h2 style="color:#b45309;">⏰ CẢNH BÁO LÔ HÀNG SẮP HẾT HẠN SỬ DỤNG</h2>
            <p>Xin chào Anh/Chị,</p>
            <p>
                Hệ thống ghi nhận hiện có <strong>{total}</strong> lô hàng
                <strong>sắp đến hạn hoặc đã quá hạn sử dụng</strong> (HSD còn dưới 60 ngày).
            </p>
            <p>Danh sách chi tiết các lô cần ưu tiên xử lý như sau:</p>
            <table style="border-collapse: collapse; margin-top: 8px; font-size: 14px;">
                <thead>
                    <tr style="background-color:#fffbeb;">
                        <th style="padding: 6px 12px; border: 1px solid #e5e7eb;">STT</th>
                        <th style="padding: 6px 12px; border: 1px solid #e5e7eb;">Lô</th>
                        <th style="padding: 6px 12px; border: 1px solid #e5e7eb;">Mã sản phẩm</th>
                        <th style="padding: 6px 12px; border: 1px solid #e5e7eb;">Tên sản phẩm</th>
                        <th style="padding: 6px 12px; border: 1px solid #e5e7eb;">Số lượng còn</th>
                        <th style="padding: 6px 12px; border: 1px solid #e5e7eb;">Ngày nhập</th>
                        <th style="padding: 6px 12px; border: 1px solid #e5e7eb;">Hạn sử dụng</th>
                        <th style="padding: 6px 12px; border: 1px solid #e5e7eb;">Cảnh báo</th>
                    </tr>
                </thead>
                <tbody>
                    {rows_html}
                </tbody>
            </table>
            <p style="margin-top:16px;">
                <strong>Đề xuất hướng xử lý:</strong>
            </p>
            <ul>
                <li><strong>Chuyển các lô sắp hết hạn sang Khu E:</strong> Khu E là khu vực dành riêng cho các mặt hàng sắp hết hạn sử dụng. Vui lòng chuyển các lô hàng này sang Khu E để dễ dàng quản lý và ưu tiên xuất hàng.</li>
                <li>Ưu tiên xuất trước các lô có hạn sử dụng gần nhất theo nguyên tắc FEFO (First-Expired-First-Out).</li>
                <li>Xem xét áp dụng chương trình khuyến mãi/giảm giá để đẩy nhanh tốc độ tiêu thụ cho các lô sắp hết hạn.</li>
            </ul>
            <p style="margin-top:8px;">
                Anh/Chị vui lòng chuyển các lô hàng sắp hết hạn sang <strong>Khu E</strong> và lên kế hoạch xuất hàng phù hợp để hạn chế tối đa hàng cận date hoặc hết hạn trong kho.
            </p>
            <p style="color:#6b7280; font-size:12px; margin-top:24px;">
                Email được gửi tự động từ hệ thống quản lý kho. Vui lòng không trả lời email này.
            </p>
        </body>
        </html>
        """

        msg = MIMEText(body, "html", "utf-8")
        msg["Subject"] = subject
        msg["From"] = sender
        msg["To"] = receiver

        with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
            server.login(sender, password)
            server.sendmail(sender, receiver, msg.as_string())

        # Ghi lại lịch sử email
        log_expiry_email_event(lot_rows)
        return True

    except Exception as e:
        st.warning(f"⚠ Không thể gửi email cảnh báo hạn sử dụng: {str(e)}")
        return False


# ======================
# CSS GIAO DIỆN
# ======================
st.markdown(
"""
<style>
/* Nền xám nhẹ cho toàn trang */
[data-testid="stAppViewContainer"] {
    background-color: #f5f5f5;
}

/* Thu gọn phần trắng ở trên cùng, cho nội dung sát header hơn */
main .block-container {
    padding-top: 1.5rem;
}

/* Card trắng dùng chung */
.alert-card {
    background-color: #ffffff;
    border-radius: 10px;
    padding: 20px;
    margin: 16px 0;
    box-shadow: 0 4px 10px rgba(15, 23, 42, 0.05);
}

/* Tag đỏ số sản phẩm dưới ROP */
.alert-tag {
    display: inline-block;
    background-color: #dc2626;
    color: #ffffff;
    padding: 4px 12px;
    border-radius: 999px;
    font-size: 12px;
    font-weight: 600;
    margin-left: 12px;
}

/* Nút primary (dùng cho Lịch sử email + Cài đặt ngưỡng cảnh báo) */
button[kind="primary"] {
    background-color: #2f5597 !important;  /* xanh đậm giống header */
    border-color: #2f5597 !important;
    color: #ffffff !important;
    font-weight: 600 !important;
}
button[kind="primary"]:hover {
    background-color: #1e3a5f !important;  /* xanh đậm hơn khi hover */
    border-color: #1e3a5f !important;
    color: #ffffff !important;
}

/* Nút xám (khu vực dưới cùng) */
button[key="resend_email_btn"],
button[key="clear_email_btn"] {
    background-color: #f3f4f6 !important;
    border-color: #e5e7eb !important;
    color: #374151 !important;
}
button[key="resend_email_btn"]:hover,
button[key="clear_email_btn"]:hover {
    background-color: #e5e7eb !important;
}

/* Bảng AgGrid: bo tròn + shadow + header xanh nhạt + hover đẹp hơn */
.ag-theme-balham {
    border-radius: 10px !important;
    overflow: hidden !important;
    box-shadow: 0 4px 10px rgba(15, 23, 42, 0.06);
    background-color: #ffffff;
}
.ag-theme-balham .ag-header {
    background: linear-gradient(to bottom, #eff3ff, #e0e7ff) !important;
    border-bottom: 1px solid #d4d4d8 !important;
}
.ag-theme-balham .ag-header-cell-text {
    font-weight: 600;
    color: #111827;
}
.ag-theme-balham .ag-row-hover {
    background-color: #eef2ff !important;
}
.ag-theme-balham .ag-row-selected {
    background-color: #dbeafe !important;
}
.ag-theme-balham .ag-cell {
    font-size: 13px;
}
</style>
""",
    unsafe_allow_html=True,
)

# ======================
# TẢI DỮ LIỆU & CẢNH BÁO
# ======================
df = load_data().copy()
if "::auto_unique_id::" in df.columns:
    df = df.drop(columns=["::auto_unique_id::"])

# Cột cảnh báo (đỏ/xanh) theo ROP
df["Cảnh báo"] = df.apply(
    lambda r: "🔴" if r["Số lượng tồn kho"] < r["Điểm đặt hàng lại (ROP)"] else "🟢",
    axis=1,
)

df["Sửa ROP"] = "✏️ Sửa"

# Đồng bộ lịch sử email theo trạng thái hiện tại (sản phẩm an toàn thì reset lịch sử)
if "Số lượng tồn kho" in df.columns and "Điểm đặt hàng lại (ROP)" in df.columns:
    safe_items = df[df["Số lượng tồn kho"] >= df["Điểm đặt hàng lại (ROP)"]]
    if not safe_items.empty:
        col_ma_sp = "Mã sản phẩm"
        safe_ids = safe_items[col_ma_sp].astype(str).tolist()
        prune_email_history_for_safe_products(safe_ids)

# Sản phẩm dưới ROP
warning_items = df[df["Số lượng tồn kho"] < df["Điểm đặt hàng lại (ROP)"]]
warning_count = len(warning_items)

# BẢNG CẢNH BÁO LÔ HÀNG SẮP HẾT HẠN
lot_alert_df = build_lot_expiry_alerts(df, days_threshold=60)

# ======================
# PHẦN LỊCH SỬ EMAIL (DI CHUYỂN LÊN ĐẦU)
# ======================
st.markdown(
    f"""
    <div style="
        display:flex; 
        align-items:center; 
        background-color: #2f5597; 
        padding: 12px 20px; 
        border-radius: 8px;
        margin-bottom: 16px;
    ">
        <h1 style="margin:0; font-size:28px; color: #ffffff;">🔔 Cảnh báo tồn kho</h1>
    </div>
    """,
    unsafe_allow_html=True
)

# Khởi tạo session state cho loại cảnh báo
if "email_history_type" not in st.session_state:
    st.session_state["email_history_type"] = "ROP"

# Tạo 2 tab để chọn loại cảnh báo và nút cài đặt
col_tab1, col_tab2, col_tab3 = st.columns([2, 2, 1])
with col_tab1:
    if st.button("📧 Lịch sử email cảnh báo ROP", use_container_width=True, key="email_history_rop_btn", type="primary" if st.session_state["email_history_type"] == "ROP" else "secondary"):
        st.session_state["show_email_history"] = True
        st.session_state["email_history_type"] = "ROP"
        st.rerun()
with col_tab2:
    if st.button("📧 Lịch sử email cảnh báo hạn sử dụng", use_container_width=True, key="email_history_expiry_btn", type="primary" if st.session_state["email_history_type"] == "EXPIRY" else "secondary"):
        st.session_state["show_email_history"] = True
        st.session_state["email_history_type"] = "EXPIRY"
        st.rerun()
with col_tab3:
    st.button("⚙️ Cài đặt ngưỡng cảnh báo", use_container_width=True, key="settings_btn", type="primary")

# Hiển thị lịch sử email dựa trên loại đã chọn
if st.session_state.get("show_email_history", False):
    st.markdown("---")
    if st.session_state["email_history_type"] == "ROP":
        st.subheader("📧 Lịch sử email cảnh báo ROP")
    else:
        st.subheader("📧 Lịch sử email cảnh báo hạn sử dụng")
    
    st.markdown('<div class="alert-card">', unsafe_allow_html=True)
    
    events = load_email_events()
    
    # Lọc events theo type
    if st.session_state["email_history_type"] == "ROP":
        # ROP: không có type hoặc type là "ROP" hoặc có "products" (events cũ)
        filtered_events = [e for e in events if e.get("type") != "EXPIRY" and "lots" not in e]
    else:
        # EXPIRY: type là "EXPIRY" hoặc có "lots"
        filtered_events = [e for e in events if e.get("type") == "EXPIRY" or "lots" in e]
    
    if not filtered_events:
        st.info("📭 Chưa có lịch sử email nào được gửi.")
    else:
        # Ô tìm kiếm theo ngày gửi
        col_search_hist, _ = st.columns([2, 4])
        with col_search_hist:
            search_hist_date = st.date_input(
                "🔎 Tìm kiếm lịch sử email theo ngày",
                value=None,
                key="email_history_search_date",
            )

        # Tạo bảng tổng hợp
        rows = []
        for idx, ev in enumerate(filtered_events):
            count = ev.get("count", len(ev.get("products", ev.get("lots", []))))
            ts = ev.get("timestamp", "N/A")
            if search_hist_date:
                date_str = search_hist_date.strftime("%Y-%m-%d")
                if not str(ts).startswith(date_str):
                    continue
            rows.append(
                {
                    "ID": idx,  # dùng nội bộ để lấy chi tiết
                    "Số mặt hàng cảnh báo": count,
                    "Thời gian gửi": ts,
                }
            )

        df_events = pd.DataFrame(rows)
        if not df_events.empty:
            # Sắp xếp theo thời gian gửi mới nhất trước
            df_events = df_events.sort_values("Thời gian gửi", ascending=False).reset_index(drop=True)
            # Thêm STT 1..N
            df_events.insert(0, "STT", range(1, len(df_events) + 1))

            # Dùng AgGrid để click chọn 1 dòng
            gb_hist = GridOptionsBuilder.from_dataframe(df_events)
            gb_hist.configure_default_column(
                cellStyle={"textAlign": "center"},
            )
            gb_hist.configure_selection("single")
            gb_hist.configure_column("ID", hide=True)
            gb_hist.configure_grid_options(domLayout="normal")

            grid_opts_hist = gb_hist.build()

            # Chiều cao bảng lịch sử email tự co theo số dòng
            row_h = 36
            header_h = 40
            pad_h = 20
            n_rows_hist = len(df_events)
            hist_height = header_h + n_rows_hist * row_h + pad_h
            hist_height = max(120, min(hist_height, 420))

            resp_hist = AgGrid(
                df_events,
                gridOptions=grid_opts_hist,
                update_mode=GridUpdateMode.SELECTION_CHANGED,
                allow_unsafe_jscode=False,
                theme="balham",
                height=hist_height,
            )

            selected_hist = resp_hist.get("selected_rows", [])
            if isinstance(selected_hist, pd.DataFrame):
                selected_hist = selected_hist.to_dict(orient="records")
            elif selected_hist is None:
                selected_hist = []

            # Nút xóa lịch sử (phía dưới bảng tổng hợp)
            col_clear1, col_clear2, col_clear3 = st.columns([2, 1, 2])
            with col_clear2:
                if st.button("🗑️ Xóa lịch sử email", key="clear_email_btn", use_container_width=True):
                    clear_email_history()
                    st.session_state["show_email_history"] = False
                    st.success("✔ Đã xóa lịch sử email!")
                    st.rerun()

            # Nếu chọn một lần gửi, hiển thị bảng chi tiết
            if len(selected_hist) > 0:
                event_row = selected_hist[0]
                event_id = int(event_row["ID"])
                if 0 <= event_id < len(filtered_events):
                    event_data = filtered_events[event_id]
                    
                    st.markdown("---")
                    if st.session_state["email_history_type"] == "ROP":
                        detail_products = event_data.get("products", [])
                        st.markdown("#### 📦 Chi tiết sản phẩm đã cảnh báo trong email")
                        
                        if detail_products:
                            df_detail = pd.DataFrame(
                                [
                                    {
                                        "Mã sản phẩm": p.get("ma_sp", ""),
                                        "Tên sản phẩm": p.get("ten_sp", ""),
                                        "Tồn kho": p.get("ton_kho", 0),
                                        "ROP": p.get("rop", 0),
                                    }
                                    for p in detail_products
                                ]
                            )
                            df_detail.insert(0, "STT", range(1, len(df_detail) + 1))
                            st.dataframe(df_detail, use_container_width=True, hide_index=True)
                        else:
                            st.info("📭 Không có dữ liệu chi tiết cho lần gửi này.")
                    else:
                        detail_lots = event_data.get("lots", [])
                        st.markdown("#### 📦 Chi tiết lô hàng đã cảnh báo trong email")
                        
                        if detail_lots:
                            # Chỉ lấy các cột: Lô, Mã sản phẩm, Tên sản phẩm, Số lượng tồn kho
                            df_detail = pd.DataFrame([
                                {
                                    "Lô": lot.get("Lô", ""),
                                    "Mã sản phẩm": lot.get("Mã sản phẩm", ""),
                                    "Tên sản phẩm": lot.get("Tên sản phẩm", ""),
                                    "Số lượng tồn kho": lot.get("Số lượng tồn kho", 0),
                                }
                                for lot in detail_lots
                            ])
                            if not df_detail.empty:
                                df_detail.insert(0, "STT", range(1, len(df_detail) + 1))
                                st.dataframe(df_detail, use_container_width=True, hide_index=True)
                        else:
                            st.info("📭 Không có dữ liệu chi tiết cho lần gửi này.")
        else:
            st.info("📭 Không có email nào trong ngày được chọn.")
    
    st.markdown('</div>', unsafe_allow_html=True)
    st.markdown("---")

# ======================
# BẢNG CẢNH BÁO LÔ HÀNG SẮP HẾT HẠN
# ======================
st.markdown('<div class="alert-card">', unsafe_allow_html=True)
st.subheader("⏰ Cảnh báo hạn sử dụng theo lô hàng")

if lot_alert_df.empty:
    st.success("✔ Hiện chưa có lô hàng nào sắp hết hạn (HSD còn dưới 60 ngày).")
else:
    gb_lot = GridOptionsBuilder.from_dataframe(lot_alert_df)
    gb_lot.configure_default_column(
        cellStyle={"textAlign": "center"},
    )
    gb_lot.configure_grid_options(domLayout="normal")

    gb_lot.configure_column("Lô", header_name="Lô")
    gb_lot.configure_column("Mã sản phẩm", header_name="Mã sản phẩm")
    gb_lot.configure_column("Tên sản phẩm", header_name="Tên sản phẩm")
    gb_lot.configure_column("Số lượng tồn kho", header_name="Số lượng tồn kho")
    gb_lot.configure_column("Ngày nhập", header_name="Ngày nhập", hide=True)  # Ẩn cột Ngày nhập
    gb_lot.configure_column("Hạn sử dụng", header_name="Hạn sử dụng", hide=True)  # Ẩn cột Hạn sử dụng
    gb_lot.configure_column("Tình trạng", header_name="Tình trạng")
    gb_lot.configure_column("Cảnh báo", header_name="Cảnh báo")
    gb_lot.configure_column("_is_in_khu_e", hide=True)  # Ẩn cột flag
    # Cột Trạng thái hiển thị màu sắc
    gb_lot.configure_column(
        "Trạng thái",
        header_name="Trạng thái",
        cellRenderer='''
            function(params) {
                const isInKhuE = params.data._is_in_khu_e;
                if (isInKhuE) {
                    return '<span style="color: #eab308; font-weight: 600;">Đã chuyển sang Khu E</span>';
                } else {
                    return '<span style="color: #dc2626; font-weight: 600;">Chưa xử lí</span>';
                }
            }
        ''',
        cellStyle={"textAlign": "center"},
    )

    lot_grid_opts = gb_lot.build()

    row_h = 36
    header_h = 40
    pad_h = 20
    n_rows_lot = len(lot_alert_df)
    lot_height = header_h + n_rows_lot * row_h + pad_h
    lot_height = max(140, min(lot_height, 420))

    AgGrid(
        lot_alert_df,
        gridOptions=lot_grid_opts,
        update_mode=GridUpdateMode.NO_UPDATE,
        allow_unsafe_jscode=True,
        theme="balham",
        height=lot_height,
    )

    # Tự động gửi email cảnh báo hạn sử dụng (chỉ gửi khi danh sách lô cảnh báo THAY ĐỔI)
    lot_records = lot_alert_df.to_dict(orient="records")
    signature_parts = [
        f"{r['Mã sản phẩm']}-{r['Lô']}-{r['Hạn sử dụng']}-{r['Số lượng tồn kho']}"
        for r in lot_records
    ]
    signature = "|".join(sorted(signature_parts))

    last_signature = load_expiry_signature()

    if signature and signature != last_signature:
        st.info(
            f"📧 Đang gửi email cảnh báo hạn sử dụng cho {len(lot_records)} lô hàng sắp hết hạn."
        )
        if send_expiry_email(lot_records):
            save_expiry_signature(signature)
            st.success("✔ Đã gửi email cảnh báo hạn sử dụng cho các lô hàng sắp hết hạn.")
        else:
            st.warning("⚠ Không thể gửi email cảnh báo hạn sử dụng, vui lòng kiểm tra cấu hình email.")
    elif signature:
        st.info("📨 Các lô hàng sắp hết hạn sử dụng đã được gửi email trước đó, chưa có thay đổi về xuất/nhập.")

st.markdown('</div>', unsafe_allow_html=True)

# ======================
# PHẦN CẢNH BÁO (DI CHUYỂN XUỐNG DƯỚI)
# ======================
st.markdown("---")

gb = GridOptionsBuilder.from_dataframe(df)

# Cột nút Sửa ROP: hiển thị chữ ✏️ Sửa, click vào sẽ chọn dòng (dùng cơ chế selection mặc định của AgGrid)
gb.configure_column(
    "Sửa ROP",
                    headerName="Sửa ROP",
                    editable=False,
                    cellRenderer='''
                        function(params){
            // Chỉ hiển thị text, để AgGrid tự xử lý click và selection của dòng
            return "✏️ Sửa";
        }
    ''',
    cellStyle={
        "textAlign": "center",
        "cursor": "pointer",
        "color": "#2563eb",
        "fontWeight": "600",
    },
)

# Cho phép chọn 1 dòng
gb.configure_selection("single")

# Cấu hình xong grid
grid_options = gb.build()

# Bọc bảng trong card trắng cho đẹp
st.markdown('<div class="alert-card">', unsafe_allow_html=True)
response = AgGrid(
    df,
    gridOptions=grid_options,
    update_mode=GridUpdateMode.SELECTION_CHANGED,   # QUAN TRỌNG: rerun khi chọn dòng
    allow_unsafe_jscode=True,
    theme="balham",
    height=500,
)
st.markdown('</div>', unsafe_allow_html=True)

# Lấy dòng được chọn
selected = response.get("selected_rows", [])

# Chuẩn hóa selected về dạng list các dict
if isinstance(selected, pd.DataFrame):
    selected = selected.to_dict(orient="records")
elif selected is None:
    selected = []

if len(selected) > 0:
    current = selected[0]
    # Nếu chọn sang sản phẩm khác thì reset xác nhận cũ
    prev = st.session_state.get("edit_item")
    if (not prev) or (prev.get("Mã sản phẩm") != current.get("Mã sản phẩm")):
        if "confirm_change" in st.session_state:
            del st.session_state["confirm_change"]
    st.session_state["edit_item"] = current


# ======================
# FORM SỬA ROP
# ======================
if "edit_item" in st.session_state:
    item = st.session_state["edit_item"]

    st.markdown("---")
    st.markdown('<div class="alert-card">', unsafe_allow_html=True)
    st.subheader(f"✏️ Thay đổi ROP cho: **{item['Tên sản phẩm']}**")

    # Key gắn với mã sản phẩm để khi chọn sản phẩm khác sẽ hiện đúng ROP tương ứng
    ma_sp = str(item["Mã sản phẩm"])
    new_rop = st.number_input(
        "Nhập ROP mới",
        min_value=0,
        value=int(item["Điểm đặt hàng lại (ROP)"]),
        key=f"new_rop_input_{ma_sp}",
        help=f"ROP hiện tại: {int(item['Điểm đặt hàng lại (ROP)'])}",
    )

    if st.button("Xác nhận thay đổi"):
        st.session_state["confirm_change"] = new_rop

    if st.session_state.get("confirm_change", None) is not None:

        st.warning("⚠ Bạn có chắc chắn muốn thay đổi ROP?")

        c1, c2 = st.columns(2)
        with c1:
            if st.button("✔ Có, cập nhật"):
                df_updated = load_data()
                index = df_updated[df_updated["Mã sản phẩm"] == item["Mã sản phẩm"]].index[0]
                df_updated.at[index, "Điểm đặt hàng lại (ROP)"] = st.session_state["confirm_change"]
                save_data(df_updated)

                del st.session_state["confirm_change"]
                del st.session_state["edit_item"]

                st.success("✔ Đã cập nhật!")
                st.rerun()

        with c2:
            if st.button("❌ Không, hủy"):
                del st.session_state["confirm_change"]
                st.info("Đã hủy thay đổi.")
                st.rerun()

    st.markdown('</div>', unsafe_allow_html=True)

# ======================
# GỬI EMAIL CẢNH BÁO (CHỈ GỬI KHI CẦN)
# ======================
if len(warning_items) > 0:
    st.markdown('<div class="alert-card">', unsafe_allow_html=True)
    st.warning(f"❌ Có {len(warning_items)} sản phẩm dưới ROP.")

    # Xác định những sản phẩm mới / có thay đổi cần kích hoạt gửi email
    items_to_send = []
    for _, r in warning_items.iterrows():
        ma_sp = str(r["Mã sản phẩm"])
        ton_kho = int(r["Số lượng tồn kho"])
        rop = int(r["Điểm đặt hàng lại (ROP)"])
        
        if should_send_email(ma_sp, ton_kho, rop):
            items_to_send.append(ma_sp)

    if items_to_send:
        # Chuẩn bị danh sách đầy đủ các sản phẩm đang dưới ROP để đưa vào email
        email_products = []
        for _, r in warning_items.iterrows():
            email_products.append(
                {
                    "ma_sp": str(r["Mã sản phẩm"]),
                    "ten_sp": r["Tên sản phẩm"],
                    "ton_kho": int(r["Số lượng tồn kho"]),
                    "rop": int(r["Điểm đặt hàng lại (ROP)"]),
                }
            )

        st.info(
            f"📧 Đang gửi email cảnh báo. Có {len(warning_items)} sản phẩm đang dưới ROP, "
            f"trong đó {len(items_to_send)} sản phẩm mới / có thay đổi."
        )

        if send_email(email_products):
            # Ghi lại LỊCH SỬ MỘT LẦN GỬI email (phục vụ xem lịch sử)
            log_email_event(email_products)

            # Sau khi gửi thành công, đánh dấu lịch sử cho TẤT CẢ sản phẩm đang dưới ROP
            for p in email_products:
                mark_email_sent(
                    ma_sp=p["ma_sp"],
                    ten_sp=p["ten_sp"],
                    ton_kho=p["ton_kho"],
                    rop=p["rop"],
                )
            st.success("✔ Đã gửi email cảnh báo tồn kho.")
        else:
            st.warning("⚠ Không thể gửi email cảnh báo, vui lòng kiểm tra cấu hình email.")
    else:
        st.info("📨 Các sản phẩm dưới ROP đã được gửi email trước đó, chưa có thay đổi tồn kho/ROP.")

    st.markdown('</div>', unsafe_allow_html=True)
else:
    st.success("✔ Tất cả sản phẩm an toàn!")
